'use client';
import {useMemo,useState} from 'react';

type Report={domain:string;confession:string;therapist:string;personality:string;strengths:string[];insecurities:string[];recommendation:string;affirmation:string;scores:{confidence:number;hoverAnxiety:number;emotionalBaggage:number;semanticHealing:number}};
const group=[['craigslist.org','I refuse to round my corners.'],['apple.com','Sometimes I think I am better than everyone.'],['myspace.com','People say they miss me, but they never visit.'],['stackoverflow.com','I did not mean to sound rude. I am just efficient.']];
export default function Home(){
 const [url,setUrl]=useState(''); const [report,setReport]=useState<Report|null>(null); const [loading,setLoading]=useState(false); const [depth,setDepth]=useState(1); const [error,setError]=useState('');
 const support=useMemo(()=>report?`${report.domain.split('.')[0]}${'-support'.repeat(depth)}.website.website`:'' ,[report,depth]);
 async function analyze(){setError('');setLoading(true);setReport(null);setDepth(1);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw new Error(d.error);setTimeout(()=>{setReport(d);setLoading(false)},900)}catch(e:any){setError(e.message);setLoading(false)}}
 return <main>
  <nav><a className="logo" href="#top"><span>◫</span>website.website</a><div><a href="#services">Services</a><a href="#group">Group therapy</a><a href="#pricing">Pricing</a></div><a className="pill" href="#session">Begin session</a></nav>
  <section id="top" className="hero shell"><p className="eyebrow">The first business-to-website studio</p><h1>Every website deserves<br/><em>its own website.</em></h1><p className="lede">Your website has spent years serving humans. We create a private digital space where it can finally feel seen, supported, and emotionally responsive.</p><a className="cta" href="#session">Build my website’s website <b>↗</b></a><div className="window"><div className="bar"><i/><i/><i/><span>yourwebsite.website.website</span></div><div className="windowBody"><small>A private space for</small><strong>yourwebsite.com</strong><blockquote>“You are more than your Lighthouse score.”</blockquote><div className="meter"><span style={{width:'87%'}}/></div><label>Website confidence <b>87%</b></label></div><div className="float f1">Emotionally responsive ✓</div><div className="float f2">0 unresolved hover issues</div></div></section>
  <div className="marquee">WEBSITE THERAPY ✦ CSS COUPLES COUNSELING ✦ DOMAIN MATCHMAKING ✦ LEGACY BROWSER HOSPICE ✦ SEMANTIC HEALING ✦</div>
  <section className="manifest shell"><p className="eyebrow">01 / The hard truth</p><h2>Your website has a website for everyone else.<br/><em>But who has a website for your website?</em></h2></section>
  <section id="session" className="session shell"><div><p className="eyebrow">02 / Begin healing</p><h2>Let us talk to<br/><em>your website.</em></h2><p>Paste a URL. We will make respectful assumptions about its emotional state.</p></div><div className="intake"><label>What is your website’s URL?</label><div className="inputRow"><span>https://</span><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==='Enter'&&analyze()} placeholder="yourwebsite.com"/><button onClick={analyze} disabled={loading||!url}>{loading?'Listening…':'Analyze →'}</button></div>{error&&<p className="error">{error}</p>}<small>Private by design. Judgmental by necessity.</small></div></section>
  {loading&&<section className="loading shell"><div className="orb"><span/><span/><span/></div><p>Asking permission…</p><h3>Your website has accepted the session.</h3></section>}
  {report&&<>
   <section className="therapy shell"><p className="eyebrow">03 / The session</p><div className="chat"><div className="who">{report.domain} has joined the chat</div><article className="siteMsg"><small>{report.domain}</small><p>“{report.confession}”</p></article><article className="therapist"><small>Website Therapist</small><p>{report.therapist}</p></article><div className="human"><input placeholder="Say something…"/><button onClick={()=>alert(`I’m sorry. This session is between me and ${report.domain}.`)}>Send</button><small>This session does not acknowledge humans.</small></div></div>
   </section>
   <section className="report shell"><div className="reportHead"><p className="eyebrow">SOULHOUSE™ REPORT</p><h2>{report.domain}</h2><span>{report.personality}</span></div><div className="scores">{Object.entries(report.scores).map(([k,v])=><div className={'score '+(k==='hoverAnxiety'?'nervous':'')} key={k}><b>{v}</b><span>{k.replace(/([A-Z])/g,' $1')}</span><div><i style={{width:v+'%'}}/></div></div>)}</div><div className="diagnosis"><article><h3>Quiet strengths</h3>{report.strengths.map(x=><p key={x}>✓ {x}</p>)}</article><article><h3>Unprocessed feelings</h3>{report.insecurities.map(x=><p key={x}>○ {x}</p>)}</article><article><h3>Care plan</h3><p>{report.recommendation}</p></article></div>
   </section>
   <section className="support shell"><div className="supportBrowser"><div className="bar"><i/><i/><i/><span>{support}</span></div><div className="supportBody"><small>THIS WEBSITE BELIEVES IN</small><h2>{depth===1?report.domain:support.replace('.website.website','')}</h2><blockquote>{depth>4?'Wait. If websites can have websites… who built yours?':`“${report.affirmation}”`}</blockquote><button onClick={()=>setDepth(d=>d+1)}>Build a website for this website →</button><p>Recursion depth: {depth}</p></div></div>{depth>1&&<div className="stack">{Array.from({length:Math.min(depth-1,5)}).map((_,i)=><span key={i} style={{transform:`translate(${i*10}px,${i*10}px)`,zIndex:-i}}/>)}</div>}</section>
  </>}
  <section id="services" className="services shell"><p className="eyebrow">04 / Clinical services</p><h2>Care for every layer<br/><em>of the stack.</em></h2><div className="cards"><article><b>01</b><h3>CSS Couples Counseling</h3><p>For stylesheets that have drifted apart.</p></article><article><b>02</b><h3>JavaScript Burnout Recovery</h3><p>Your event listeners cannot keep listening forever.</p></article><article><b>03</b><h3>Legacy Browser Hospice</h3><p>IE11 had a good run. Let us say goodbye.</p></article><article><b>04</b><h3>SSL Self-Love Certificate</h3><p>Security begins with trusting yourself.</p></article></div></section>
  <section id="group" className="group shell"><p className="eyebrow">05 / Group therapy</p><h2>No website heals<br/><em>in isolation.</em></h2><div className="circle"><div className="chair center">Hi, websites.</div>{group.map(([name,msg],i)=><div className={'chair c'+i} key={name}><strong>{name}</strong><p>{msg}</p></div>)}<div className="chair ie"><strong>internetexplorer.com</strong><p>still connecting…</p></div></div></section>
  <section id="pricing" className="pricing shell"><p className="eyebrow">06 / Invest in emotional uptime</p><h2>Transparent pricing.<br/><em>No hidden feelings.</em></h2><div className="priceCards"><article><span>Starter</span><b>$0</b><p>One website for one website.</p></article><article className="featured"><span>Professional</span><b>$9</b><p>A website for your website’s website.</p><button>Over-support my website</button></article><article><span>Enterprise</span><b>Let’s talk</b><p>A website for every page on your website.</p></article></div></section>
  <footer><div className="logo"><span>◫</span>website.website</div><p>Proudly hosted on another website.</p><small>© 2026 Certified Digital Nurturing</small></footer>
 </main>
}
